sudo: required

language: python
python:
    - "3.6"

services:
    - docker

before_install:
    - docker build -t blog:python-3.6.4 ./deploy/Dockerfiles/python

script:
    - docker run --name blog_python -d -v /home/travis/build/vernvern/blog/log:/opt/log -v  /home/travis/build/vernvern/blog:/opt/src blog:python-3.6.4
    - docker ps
    - docker inspect blog_python
    - docker exec -it blog_python nosetests -v --with-coverage --cover-package=blog --cover-xml

after_success:
    - docker exec -it blog_python pip3 install coveralls
    - docker exec -it blog_python coveralls
