---

- name: docker build python
  docker_image:
    name: blog:python-3.6.4
    path: "{{ dockerfile_path_python }}"
    pull: yes

- name: python`s docker run
  docker_container: 
    name: blog_python
    image: blog:python-3.6.4
    volumes:
    - /opt/log:/opt/log
    - /opt/src/blog:/opt/src/blog
    networks:
      - name: docker_newwork
        ipv4_address: 192.168.1.3
